// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/fund.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/fund.go -destination=internal/mocks/service/fund_mock.go -package=service_mocks
//

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	context "context"
	model "private-markets-api/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFundServiceInterface is a mock of FundServiceInterface interface.
type MockFundServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFundServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockFundServiceInterfaceMockRecorder is the mock recorder for MockFundServiceInterface.
type MockFundServiceInterfaceMockRecorder struct {
	mock *MockFundServiceInterface
}

// NewMockFundServiceInterface creates a new mock instance.
func NewMockFundServiceInterface(ctrl *gomock.Controller) *MockFundServiceInterface {
	mock := &MockFundServiceInterface{ctrl: ctrl}
	mock.recorder = &MockFundServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundServiceInterface) EXPECT() *MockFundServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFundServiceInterface) Create(ctx context.Context, name string, vintageYear int, targetSizeUSD float64, status string) (model.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, vintageYear, targetSizeUSD, status)
	ret0, _ := ret[0].(model.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFundServiceInterfaceMockRecorder) Create(ctx, name, vintageYear, targetSizeUSD, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFundServiceInterface)(nil).Create), ctx, name, vintageYear, targetSizeUSD, status)
}

// Get mocks base method.
func (m *MockFundServiceInterface) Get(ctx context.Context, id string) (model.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFundServiceInterfaceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFundServiceInterface)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockFundServiceInterface) List(ctx context.Context) ([]model.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFundServiceInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFundServiceInterface)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockFundServiceInterface) Update(ctx context.Context, id, name string, vintageYear int, targetSizeUSD float64, status string) (model.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, vintageYear, targetSizeUSD, status)
	ret0, _ := ret[0].(model.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFundServiceInterfaceMockRecorder) Update(ctx, id, name, vintageYear, targetSizeUSD, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFundServiceInterface)(nil).Update), ctx, id, name, vintageYear, targetSizeUSD, status)
}
