// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/investment.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/investment.go -destination=internal/mocks/service/investment_mock.go -package=service_mocks
//

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	context "context"
	model "private-markets-api/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInvestmentServiceInterface is a mock of InvestmentServiceInterface interface.
type MockInvestmentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInvestmentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockInvestmentServiceInterfaceMockRecorder is the mock recorder for MockInvestmentServiceInterface.
type MockInvestmentServiceInterfaceMockRecorder struct {
	mock *MockInvestmentServiceInterface
}

// NewMockInvestmentServiceInterface creates a new mock instance.
func NewMockInvestmentServiceInterface(ctrl *gomock.Controller) *MockInvestmentServiceInterface {
	mock := &MockInvestmentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockInvestmentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvestmentServiceInterface) EXPECT() *MockInvestmentServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateInvestment mocks base method.
func (m *MockInvestmentServiceInterface) CreateInvestment(ctx context.Context, fundID, investorID string, amountUSD float64, investmentDate string) (model.Investment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvestment", ctx, fundID, investorID, amountUSD, investmentDate)
	ret0, _ := ret[0].(model.Investment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvestment indicates an expected call of CreateInvestment.
func (mr *MockInvestmentServiceInterfaceMockRecorder) CreateInvestment(ctx, fundID, investorID, amountUSD, investmentDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvestment", reflect.TypeOf((*MockInvestmentServiceInterface)(nil).CreateInvestment), ctx, fundID, investorID, amountUSD, investmentDate)
}

// GetInvestmentsByFundID mocks base method.
func (m *MockInvestmentServiceInterface) GetInvestmentsByFundID(ctx context.Context, fundID string) ([]model.Investment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvestmentsByFundID", ctx, fundID)
	ret0, _ := ret[0].([]model.Investment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvestmentsByFundID indicates an expected call of GetInvestmentsByFundID.
func (mr *MockInvestmentServiceInterfaceMockRecorder) GetInvestmentsByFundID(ctx, fundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvestmentsByFundID", reflect.TypeOf((*MockInvestmentServiceInterface)(nil).GetInvestmentsByFundID), ctx, fundID)
}
