// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/investor.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/investor.go -destination=internal/mocks/service/investor_mock.go -package=service_mocks
//

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	context "context"
	model "private-markets-api/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInvestorServiceInterface is a mock of InvestorServiceInterface interface.
type MockInvestorServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInvestorServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockInvestorServiceInterfaceMockRecorder is the mock recorder for MockInvestorServiceInterface.
type MockInvestorServiceInterfaceMockRecorder struct {
	mock *MockInvestorServiceInterface
}

// NewMockInvestorServiceInterface creates a new mock instance.
func NewMockInvestorServiceInterface(ctrl *gomock.Controller) *MockInvestorServiceInterface {
	mock := &MockInvestorServiceInterface{ctrl: ctrl}
	mock.recorder = &MockInvestorServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvestorServiceInterface) EXPECT() *MockInvestorServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvestorServiceInterface) Create(ctx context.Context, name, investorType, email string) (model.Investor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, investorType, email)
	ret0, _ := ret[0].(model.Investor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvestorServiceInterfaceMockRecorder) Create(ctx, name, investorType, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvestorServiceInterface)(nil).Create), ctx, name, investorType, email)
}

// Get mocks base method.
func (m *MockInvestorServiceInterface) Get(ctx context.Context, id string) (model.Investor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Investor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInvestorServiceInterfaceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInvestorServiceInterface)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockInvestorServiceInterface) List(ctx context.Context) ([]model.Investor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Investor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInvestorServiceInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvestorServiceInterface)(nil).List), ctx)
}
